### ISSUE TITLE
Unable to access Webhooks & Scheduled Events from Settings

### ISSUE THREAD

**Issue by zaheer-srushty** [The-Commit-Company/Raven#1001]
I'm not sure which build broke it but I don't see a link to webhooks and scheduled events in the new settings page. I have System Manager role enable for my user as well as server script enabled.

**Comment by nikkothari22** [comment]
@zaheer-srushty We have removed the two settings pages in v1.6.0 . We'll add Webhooks back after making some design changes, but the scheduled events will be removed since Server Scripts might soon be deprecated in Frappe in favour of File based files (https://github.com/frappe/frappe/issues/26385). We'll have to write our own scheduled messages logic. You can still write Webhooks and Server scripts in the backend via Desk.

**Comment by zaheer-srushty** [comment]
@nikkothari22 Can you bring this feature back? Looks like there hasn't been much progress on deprecating Server Scripts. Let's have it until a firm direction has been taken by the Frappe team.
