### ISSUE TITLE
Desk not working

### ISSUE THREAD

**Issue by git-avc** [The-Commit-Company/raven#1200]
(FC) After updating both Frappe Framework (develop, last commit 0f546c3) and Raven (develop, cf1a9aa) desk is not loading.

Got this on console
`mysite.com/raven_chat.bundle.jsx 404 (Not Found)`

![image](https://github.com/user-attachments/assets/acb2b1da-ae25-4635-ba19-f2bdc8962c47)

Uninstalling Raven site back to life.
Anyone else?

**Comment by nikkothari22** [comment]
Maybe bench build did not run properly?

**Comment by git-avc** [comment]
Yeah. Seems some FC issue ... After rebuilding assets Raven is working again ...
Thanks @nikkothari22 . Closing.

**Comment by marcoantonio123456** [comment]
on Frappe Cloud, on every new reinstall I get this issue. Support wants me to create a new bench and move my site since they don't allow asset rebuilding as a command on ssh (maybe it's too memory intense). Best part is that they need to authorize ssh access on new bench groups I think, since. Either way hoping this can be looked into @nikkothari22

App is great btw

**Comment by nikkothari22** [comment]
I'll look into this. The desk integration has not been maintained at all. 

Can you tell me which version of Frappe you're using? The nightly build or v15? 

For now you can disable the desk integration by going to Raven Settings, till I figure out how to fix this.

**Comment by marcoantonio123456** [comment]
> Can you tell me which version of Frappe you're using? The nightly build or v15?

Framework: v16.0.0-dev (HEAD)

> For now you can disable the desk integration by going to Raven Settings, till I figure out how to fix 

Thank you! will do
