### ISSUE TITLE
Warnings in Installation and App not accessible at mysite/raven-app

### ISSUE THREAD

**Issue by Ionic-Info** [The-Commit-Company/Raven#210]
Tried installing. The app is installed with some warnings. Doctypes are accessible. But the app isnt available at mysite/raven-app.

```
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
warning swr@2.0.3: The engine "pnpm" appears to be invalid.
[3/4] Linking dependencies...
warning " > @chakra-ui/icons@2.0.17" has unmet peer dependency "@chakra-ui/system@>=2.0.0".
warning "@chakra-ui/icons > @chakra-ui/icon@3.0.16" has unmet peer dependency "@chakra-ui/system@>=2.0.0".
warning "@emotion/react > @emotion/babel-plugin@11.10.5" has unmet peer dependency "@babel/core@^7.0.0".
warning "@emotion/react > @emotion/babel-plugin > @babel/plugin-syntax-jsx@7.18.6" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > chakra-react-select@4.6.0" has unmet peer dependency "@chakra-ui/form-control@^2.0.0".
warning " > chakra-react-select@4.6.0" has unmet peer dependency "@chakra-ui/icon@^3.0.0".
warning " > chakra-react-select@4.6.0" has unmet peer dependency "@chakra-ui/layout@^2.0.0".
warning " > chakra-react-select@4.6.0" has unmet peer dependency "@chakra-ui/media-query@^3.0.0".
warning " > chakra-react-select@4.6.0" has unmet peer dependency "@chakra-ui/menu@^2.0.0".
warning " > chakra-react-select@4.6.0" has unmet peer dependency "@chakra-ui/spinner@^2.0.0".
warning " > chakra-react-select@4.6.0" has unmet peer dependency "@chakra-ui/system@^2.0.0".
warning " > frappe-react-sdk@1.0.25" has unmet peer dependency "swr@^2.0.0".
warning " > quill-linkify@0.3.0" has unmet peer dependency "quill@^1.3.7".
warning " > quill-linkify@0.3.0" has unmet peer dependency "quill-delta@^3.6.2 || ^4.2.2".
[4/4] Building fresh packages...
Done in 36.85s.
Done in 37.41s.
```

**Comment by nikkothari22** [comment]
Hey @Ionic-Info 

We are still cleaning up the codebase and making some performance improvements. We should be done by the end of the week. 

And I believe the app should be accessible on /raven (we changed it recently). @janhvipatil can confirm.

**Comment by janhvipatil** [comment]
@Ionic-Info was the issue fixed for you?

**Comment by Ionic-Info** [comment]
Raven Works ... but receipt of chat is not updated till browser refresh. On the same lines there's no notification of any kind regarding new messages either on channels or direct messages. Settings shows a blank page.

**Comment by Ionic-Info** [comment]
didnt raise issue for the above as @nikkothari22 had suggested that the app is being worked on.

**Comment by nikkothari22** [comment]
> receipt of chat is not updated till browser refresh.
> 
> 

@Ionic-Info can you elaborate on this?

**Comment by Ionic-Info** [comment]
New messages sent on channel or direct message by another user appear only after browser refresh. Also no notification of any new message. I have tried in Brave browser(chromium based). Shall check if its the same on Firefox.

**Comment by nikkothari22** [comment]
Thanks @Ionic-Info 

About the messages not being fetched when someone else sends it - I guess we have to debug our web socket events. We just released a new version of frappe-react-SDK that supports this out of the box, so we'll try fixing this over the weekend. We also need to optimise our use of web sockets by making users join and leave "rooms" - in our case channels so that they do not receive events for all messages being sent on Raven in other channels.

As far as notifications go, we haven't made that feature yet. To do this, we would have to figure out if a user has read a particular message - so that we can show an unread message count for every channel. This is something we're still working on architecture-wise. Push notifications are something that we're looking at as well - but for that we'll need to integrate something like Firebase - and would need to allow users to link their Firebase accounts with Raven.
