### ISSUE TITLE
Contact images are not shown to users who do not have System Manager role 

### ISSUE THREAD

**Issue by Adilolge98** [The-Commit-Company/Raven#427]

**Comment by nikkothari22** [comment]
We need to do the following to get around this:

- [ ] Add an `on_update` document hook to create/update a Raven user when a user with the "Raven User" role is modified.
- [ ] Create a new Doctype called "Raven User" with full_name, name, user_image. Naming scheme will be same as the User doctype. There will be a link field to the User Doctype
- [ ] Change the Raven Channel Member, Message and Reaction doctypes to now use "Raven User" instead of User. This will cause a breaking change since existing installations will not have any Raven Users
- [ ] To avoid the breaking change, create a migration patch that creates Raven Users for all users with the role "Raven User" on the site.
- [ ] Modify the `get_list` API and the `get_channel_members` API to join the Raven User Doctype and not the User doctype

Keeping the data structure same, there should be no changes required on the frontend for this. Just the data source is changing.
