### ISSUE TITLE
User who is not member of private channel can be mentioned 

### ISSUE THREAD

**Issue by Suraj787** [The-Commit-Company/Raven#460]
In a private channel, we grant access exclusively to invited members who can mention each other. However, currently  in the private channel, any Raven user can be mentioned without these restrictions.

**Comment by nikkothari22** [comment]
Yeah this is as per design. Slack follows the same.

The idea is that you can mention any user in the system on any channel for better context. For example, there might be 6 people named "Alex" in an org, but you want to mention one of them in your channel. Better to use mentions for this. 

We haven't implemented mention notifications yet, but when we do, these users won't get notified since they don't belong to the channel.

**Comment by Suraj787** [comment]
@nikkothari22
 if there are six people named Alex, and only one is a member of my private channel, there's a risk of accidentally mentioning one of the other five. This can become problematic, especially when we implement notifications because the intended recipient might not receive the notification. Allowing mentions of non-members in a private channel seems to undermine the intended functionality of mentions and sending notifications for mentions.

**Comment by nikkothari22** [comment]
We plan to add markers in the mention block (maybe we'll use TipTap) that show if the user is a member or not - with members being shown first on the list when you try to mention someone. 

But this is something that we saw on Slack as well wherein you could mention any user in any channel - including DMs.

Notifications are just one aspect of this. The bigger picture is integrations. When we build out our integration bots, we'll be able to tell certain "Raven bots" to do something for a particular user. For example, "Send this document via email to "@Alex"" 

Slack has this concept of Bots which allow you to pass user context commands to the bot itself. Super useful and a feature that power users would love. In such cases, it doesn't matter if the user is a member of the channel or not.

Regardless, I get your point of accidentally selecting a user who isn't a member of the channel. Since we don't have notifications now, it doesn't matter. But yes, when we do add mention notifications, we'll have to fix the UI to show members first to avoid errors.
