### ISSUE TITLE
[RAV-15] Web Push Notifications

### ISSUE THREAD

**Issue by TITANiumRox** [The-Commit-Company/Raven#547]
Steps to implement web push notifications:

1. Create a Service Worker
2. Get permission from user to receive push messages
3. Get PushSubscription object:

* VAPID keys: Generate the VAPID keys, can be done using any tool online or offline. Store these keys in the Frappe database. The private key should be kept secret.
* Client subscribes to push notifications: When a client wants to subscribe to push notifications, the server will send the public key to the client.
* Client registers with the browser’s push service: The client then uses this public key to register with the browser’s push service. The push service returns the PushSubscription object to the client.

1. Send subscription to frappe server and save in database
2. Send a Web Push Protocol request from frappe server to the Push Service

Notification should be received on the subscribed browser after the Web Push Protocol request is parsed and authenticated by the Push Service.

![image](https://uploads.linear.app/f9751e49-d925-4c82-a5c4-00bbe680d813/a9a7d848-e371-4d0a-abd1-17f30c76cbf4/dc3e0f12-07d3-433d-bd8d-69d4affa05bc?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2Y5NzUxZTQ5LWQ5MjUtNGM4Mi1hNWM0LTAwYmJlNjgwZDgxMy9hOWE3ZDg0OC1lMzcxLTRkMGEtYWJkMS0xN2YzMGM3NmNiZjQvZGMzZTBmMTItMDdkMy00MzNkLWJkOGQtNjlkNGFmZmEwNWJjIiwiaWF0IjoxNzAyMjEwNzkwLCJleHAiOjE3MDIyOTcxOTB9.uWVN2e7wptidKlEmzrPayPNcVsT7JNxAQItL5rxULfI)

<sub>From [SyncLinear.com](https://synclinear.com) | [RAV-15](https://linear.app/the-commit-company/issue/RAV-15/web-push-notifications)</sub>

**Comment by yahyaoudra** [comment]
Hey is this feature to receive messages notification ?

**Comment by nikkothari22** [comment]
> Hey is this feature to receive messages notification ? @TITANiumRox @nikkothari22 

Yes. We're working on it.

We're trying one way to send web push notifications on Raven, while the FrappeHR team is also trying a different way. Hopefully, we'll have web push notification support in Frappe framework itself (probably powered by Frappe Cloud).

**Comment by SalaAl-Homikany** [comment]
> > Hey is this feature to receive messages notification ? @TITANiumRox @nikkothari22 
> 
> Yes. We're working on it.
> 
> We're trying one way to send web push notifications on Raven, while the FrappeHR team is also trying a different way. Hopefully, we'll have web push notification support in Frappe framework itself (probably powered by Frappe Cloud). 

What about now? Did the attempt to send notifications via the web succeed?

**Comment by nikkothari22** [comment]
> What about now? Did the attempt to send notifications via the web succeed?

Yeah we tried one approach where we don't use FCM and just did it directly via web push API. That worked on some browsers but not all.

On the other hand, the Frappe HR team have set up a relay server for notifications. That seemed to work on all browsers and we only need to implement it and test it on Raven which we're doing now. This would however work easily on Frappe Cloud since the relay server is on FC, but won't work when self hosting Raven. 

For self hosting, users would also have to deploy the relay server app and the FCM config themselves. I'm not sure if that can run on the same server or not, but we'll provide documentation for this once the relay server app is tested and released.

This is also dependent on the Frappe framework itself - since the common controller is in FF, and hence push notifications might not work on older versions of Frappe framework.
