### ISSUE TITLE
[RAV-10] Does raven support notification sound on the browser

### ISSUE THREAD

**Issue by yahyaoudra** [The-Commit-Company/Raven#555]
Does raven support notification sound on the browser ?

<sub>[RAV-10](https://linear.app/the-commit-company/issue/RAV-10/does-raven-support-notification-sound-on-the-browser)</sub>

**Comment by nikkothari22** [comment]
Not yet. We have it in our plan but we are focusing on performance and UI right now.

Moreover, for sounds, we need to find a cool sound file first - one that resonates with the Raven brand. 

Will keep this in the backlog.

**Comment by yahyaoudra** [comment]
Hi @nikkothari22  Thank you for those information, good luck with that.
Raven So far is performing very well. we are planning to make it our main communication tool.
I suggest you this cool notification sound as you know teams could send many messages and but you have to stay informed instead of annoyed. this one is short and soft https://elements.envato.com/message-notification-WCSC5KW find it attached with its license.
Thank you.
[message-notification-2023-11-27-04-51-55-utc.zip](https://github.com/The-Commit-Company/Raven/files/13505271/message-notification-2023-11-27-04-51-55-utc.zip)

**Comment by nikkothari22** [comment]
@yahyaoudra Will check it out. Ideally we want an open source licensed sound file. 

This will require some work since we need to add settings and preferences for users (both on a global level and on a channel level) 

Glad to know it's performing well for you. We're pushing a big update this Sunday which will improve performance even more. Are you using Raven with ERPNext? (We really need to have a community where we can discuss ideas etc)

**Comment by yahyaoudra** [comment]
@nikkothari22 Yeah, it will take some time.
I'm glad to hear that; I love updates 😅.
Previously, we were using it as a separate Frappe installation, but we've encountered some UX issues (such as users having to log in twice on different systems and migrating users, etc.). Now, we are using it with ERPnext v15.
I would love to participate in these discussions, as my role as a product manager involves ideation, discussions, and development.
