### ISSUE TITLE
Change naming for Raven Message to autoincrement

### ISSUE THREAD

**Issue by nikkothari22** [The-Commit-Company/Raven#751]
Would it be ideal to name the message Doctype using autoincrement instead of a random hash? I’m not sure if that helps while sorting/pagination.

My assumption is that an integer based naming scheme would be easier to sort by, and also we wouldn’t necessarily need to sort messages by creation - can do it just by the primary key.

If yes, how can we switch from random hash to autoincrement since I think that will break existing messages right? 

Thoughts @nagariahussain @ankush?

**Comment by ankush** [comment]
> If yes, how can we switch from random hash to autoincrement since I think that will break existing messages right? 

This is very hard if they are linked to something else, otherwise not so much. 

https://github.com/frappe/frappe/pull/25309 this kinda solves some of the problem with random naming. Not all. The autoincrement implementation isn't that great either (str<>int gotchas and mysql casting incorrectly sometimes)

**Comment by nikkothari22** [comment]
Messages are linked to reactions so probably not worth the effort right now.
Fix/improvement in the framework itself mostly solves the problem of messages within the same timeframe being closer together.
