### ISSUE TITLE
Mobile app installation

### ISSUE THREAD

**Issue by prasanth1166** [The-Commit-Company/Raven#804]
Hi Team,
Currently we are using the Raven application in our project. We also want the mobile app of the Raven.

Can someone guide how to do the setup and create the apk for using the Raven Mobile application.

https://github.com/The-Commit-Company/Raven/tree/develop/mobile

**Comment by prasanth1166** [comment]
I dont have the access to above mentioned installation link

**Comment by nikkothari22** [comment]
Hey @prasanth1166 

The Raven Mobile app is a progressive web app. 

On your phone browser, go to `/raven_mobile` on your site - so if your site is hosted on `example.frappe.cloud`, go to `example.frappe.cloud/raven_mobile` . The mobile app will open up in your browser. Since it's a PWA, you can install it directly from the browser (https://inspire.microsoft.com/en-US/web-app-install)
