### ISSUE TITLE
Poll Enhancements

### ISSUE THREAD

**Issue by NagariaHussain** [The-Commit-Company/Raven#805]
* Retract Vote

![telegram-cloud-photo-size-5-6082403144542830062-y](https://github.com/The-Commit-Company/Raven/assets/34810212/e7003097-9dfe-419a-985f-5a855f65bc40)

* How do I view the folks who have voted in a non-anonymous poll?

**Comment by rmehta** [comment]
non anonymous votes - we use it to check who is coming to office today.

**Comment by janhvipatil** [comment]
Yes, will take this up today.

**Comment by janhvipatil** [comment]
Showing votes on web app is remaining.

**Comment by rmehta** [comment]
Basic question. Why not responsive app, will cut engineering effort by 30%

**Comment by nikkothari22** [comment]
The interactions on the mobile app are very different from the web app (e.g.: hold to open bottom drawer on mobile vs right click to open small context menu on web)

Plus, we started building this during FOSSHack so we took a shortcut back then to build two separate apps. 

However, now we're probably going to build a native app with React Native because of lots of issues: #824 , #813 and many more on the PWA (mobile) - mostly because of the limited capabilities that are available on a PWA blocked by the two big tech giants and the non-standard behaviour of PWAs on both iOS and Android (they just don't behave the same way).

**Comment by janhvipatil** [comment]
closing as completed
