### ISSUE TITLE
Channels per user role type and per department of the company

### ISSUE THREAD

**Issue by SamuelLHuber** [The-Commit-Company/raven#928]
Hello, thank you for building Raven!

Would love to create private channels that are automatically assigned to users based on their roles in Frappe/ERPNext.

We have many different departments and would love to make the user role e.g. Sales have their own private channel that other people can't see unless they have been manually added or have the role.

same goes for our internal departments. Webdesign shouldn't see the video production departments channel.

Manually adding/removing users if they leave the company or change roles is cumbersome.

Same goes for projects, would love to create a project in ERPNext and then create a channel for it with the assigned people to the project so the team + customer can communicate together in Raven.

Cheers,
Samuel

**Comment by nikkothari22** [comment]
Hey @SamuelLHuber, 

As of now, these can be done via Raven Bots and some Python scripts in a custom app, but we can build a native ERPNext integration in Raven itself.

As far as I understand, you want to:

1. Create a private channel when a new project is created. When a user is added to the project, add them to said channel. We will have to understand how the Project module works in ERPNext. 
2. Create a private channel for each department, and add the employees in that department to the channel. If the department changes, then remove the employee from the channel. This would be an integration with ERPNext and FrappeHR.

I don't think this can be done directly via "Roles" since the role itself is dependent on how the admins have configured it. What we can do is use standard DocTypes/fields in ERPNext/HR like Department, Employee, Project and use that to create Raven Channels. 

Is my understanding correct?

**Comment by SamuelLHuber** [comment]
Cheers @nikkothari22 thanks for the fast reply, is there documentation available on the bots? have some ideas where I'd like to run them too, outside of the above.

Regarding 

1) yes, but not high priority

Project has users in the [Project DocType](https://github.com/frappe/erpnext/blob/develop/erpnext/projects/doctype/project/project.json) which would work well to pull the users which should have access

2) yes! exactly. If not available via roles the department doctype would suffice

though users are also available programmatically [Employee Doctype](https://github.com/frappe/erpnext/blob/develop/erpnext/setup/doctype/employee/employee.json)

Department is available [in Code here](https://github.com/frappe/erpnext/blob/develop/erpnext/setup/doctype/department/department.json)

**Comment by nikkothari22** [comment]
Awesome! 

We'll add native integrations for both those scenarios next week, but would like some assistance in testing it maybe since we don't use projects/departments ourselves. 

Regarding Raven Bots: we haven't added docs yet, but it works something like this: 

```
my_bot = frappe.get_doc("Raven Bot", "my-bot")

my_bot.send_message(...)
```

The methods are available here: 

https://github.com/The-Commit-Company/Raven/blob/develop/raven/raven_bot/doctype/raven_bot/raven_bot.py

Create the bot first (it's a Doctype), and if using a custom app, just export it as a fixture.

**Comment by SamuelLHuber** [comment]
For sure will be available to test. Thank you! Great to hear that.

For the progressive web app at raven_mobile we didn't get a settings toggle for push notifications and not recieving them. How do we set these up? the profile page doesn't have anything would have expected an "enable notifications" toggle there. 

PS: Saw on the webpage push notifications coming later this year, if there's something we can do to aid make that available earlier please let us know.

**Comment by nikkothari22** [comment]
> For the progressive web app at raven_mobile we didn't get a settings toggle for push notifications and not recieving them. How do we set these up? the profile page doesn't have anything would have expected an "enable notifications" toggle there. 


On Raven Mobile, the push notification toggle will appear on the settings page only when:

1. The PWA is "installed" on the device
2. Push notifications are enabled via "Push Notification Settings". This is a Frappe framework feature. If you're on Frappe Cloud, your site will connect to a relay server for push messages automatically. If you're self hosting, you'll have to host the relay server - that's another Frappe app which is not yet open sourced and is managed by Frappe. 

PS: we're going to deprecate the separate mobile PWA and make the web app work on mobile devices as a responsive web app. There's an open PR for that.

**Comment by SamuelLHuber** [comment]
nice, enabled, so testing Push Notifications now, see it in settings. Thank you

**Comment by SamuelLHuber** [comment]
<img width="611" alt="Screenshot 2024-07-12 at 12 53 11" src="https://github.com/user-attachments/assets/37346a56-cd6f-4184-a3c2-5d6553977919">

can't see where to add / link when creating a channel

**Comment by nikkothari22** [comment]
The department channels will get auto created when a department is created. You need to enable this in Raven Settings.

**Comment by SamuelLHuber** [comment]
<img width="351" alt="Screenshot 2024-07-12 at 13 55 54" src="https://github.com/user-attachments/assets/d445e3f0-dada-4e27-aa03-195a1d1f8e9a">

I don't see a toggle in the raven settings using /app/raven-settings/Raven Settings

though in /app/department I see 13 departments and the all departments group

**Comment by nikkothari22** [comment]
Are you on the main branch or develop branch?

**Comment by SamuelLHuber** [comment]
main

**Comment by nikkothari22** [comment]
Oh okay. Yeah, we were testing this feature on develop. Will release it.

**Comment by nikkothari22** [comment]
@SamuelLHuber this is now available in the latest release of Raven.

**Comment by SamuelLHuber** [comment]
> @SamuelLHuber this is now available in the latest release of Raven.

thank you! new release feels really snappy on Web.

 open, everyone is a member. is lovely

departments channels after I activate it isn't created for existing departments but works well for creating and deleting departments

**Comment by blaggacao** [comment]
@nikkothari22 
![image](https://github.com/user-attachments/assets/7268a7ee-e11c-4699-9262-eb765749df3a)

As it is presented, it appears that this only works when installed with HRMS app, but as far as I understand, it doesn't depend on Frappe HRMS.

**Comment by nikkothari22** [comment]
@blaggacao Yes, that's the plan eventually. We'll add more app integrations and then organize them into better sections. We might need separate "sections" for HR and Payroll as well. Haven't thought about it as of now, but the layout would definitely change.

**Comment by nikkothari22** [comment]
Completed via #966
