### ISSUE TITLE
Raven app is getting logout on every next day

### ISSUE THREAD

**Issue by midhat2020** [The-Commit-Company/Raven#980]
App always logout after sometimes so we won't get notification also because we get the notification only on login so this is a huge issue for us.

**Comment by PhantomKunai** [comment]
Noticing the same on mobile. Specifically iOS. Dont know if there some specific settings we should change.

**Comment by nikkothari22** [comment]
Yeah, we faced the same issue. The problem is that the PWA uses cookies, which have an expiry set in System Settings. The fix we found was increasing the session timeout in System Settings. If this is on Frappe School chat, I'll ask @NagariaHussain to increase the session timeout. 

<img width="1242" alt="image" src="https://github.com/user-attachments/assets/f793f3b3-3ca7-4beb-b3ad-2d5215a0dcac">

**Comment by ahmadRagheb** [comment]
i have the same issue , the number 170:00 means 7 days , i keep logining me out every day . ???

**Comment by ahmadRagheb** [comment]
@nikkothari22 can you reopen this issue

**Comment by nikkothari22** [comment]
@ahmadRagheb  is this happening on the PWA or the new native mobile app ?
